In [1]:
import numpy as np

In [11]:
a=[0,1,2,3,4,5]
b=[1,4,9]
a=np.array(a).reshape(2,3)
b=np.array(b)
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[1 4 9]


In [3]:
print(a*b)

[[ 0  4 18]
 [ 3 16 45]]


In [16]:
a=np.arange(2*1*7*3).reshape(2,1,7,3)  # 2*1*7*3 Matrix 생성
b=np.arange(1*5*1*3).reshape(  5,1,3)  # 5*1*3 Matrix 생성

In [17]:
print(a*b)

[[[[  0   1   4]
   [  0   4  10]
   [  0   7  16]
   [  0  10  22]
   [  0  13  28]
   [  0  16  34]
   [  0  19  40]]

  [[  0   4  10]
   [  9  16  25]
   [ 18  28  40]
   [ 27  40  55]
   [ 36  52  70]
   [ 45  64  85]
   [ 54  76 100]]

  [[  0   7  16]
   [ 18  28  40]
   [ 36  49  64]
   [ 54  70  88]
   [ 72  91 112]
   [ 90 112 136]
   [108 133 160]]

  [[  0  10  22]
   [ 27  40  55]
   [ 54  70  88]
   [ 81 100 121]
   [108 130 154]
   [135 160 187]
   [162 190 220]]

  [[  0  13  28]
   [ 36  52  70]
   [ 72  91 112]
   [108 130 154]
   [144 169 196]
   [180 208 238]
   [216 247 280]]]


 [[[  0  22  46]
   [  0  25  52]
   [  0  28  58]
   [  0  31  64]
   [  0  34  70]
   [  0  37  76]
   [  0  40  82]]

  [[ 63  88 115]
   [ 72 100 130]
   [ 81 112 145]
   [ 90 124 160]
   [ 99 136 175]
   [108 148 190]
   [117 160 205]]

  [[126 154 184]
   [144 175 208]
   [162 196 232]
   [180 217 256]
   [198 238 280]
   [216 259 304]
   [234 280 328]]

  [[189 220 253]
   [216 250 2