## import

In [1]:
import numpy as np
import sys,os
import random
import matplotlib.pyplot as plt
import csv
import ast
from collections import OrderedDict

## Input Data 생성

x, y, z 데이터 중 

x가 0~99이면    정답 => [1,0,0]

x가 100~199이면 정답 => [0,1,0]

x가 200~299이면 정답 => [0,0,1]

In [2]:
input_data=np.empty((0,3))
t=np.empty((0,3))
for i in range(5000):
    input_data=np.append(input_data, np.array([[random.randrange(0,300) for j in range(3)]]),axis=0)
    x=input_data[-1,0]
    if x<100:
        t=np.append(t,np.array([[1, 0, 0]]),axis=0)
    elif x<200:
        t=np.append(t,np.array([[0, 1, 0]]),axis=0)
    elif x<300:
        t=np.append(t,np.array([[0, 0, 1]]),axis=0)
print(input_data.shape)

(5000, 3)


추가미션

R, G, B 순서대로 나열 된 데이터 t->(0,0,1),(0,0,1),(0,0,1),(0,0,1).....(0,1,0),(0,1,0),(0,1,0),(0,1,0)....(1,0,0),(1,0,0),(1,0,0),(1,0,0)

In [ ]:
input_data=np.empty((0,3))

ax=np.empty((0,3))
bx=np.empty((0,3))
cx=np.empty((0,3))
order_xyz=np.empty((0,3))

at=np.empty((0,3))
bt=np.empty((0,3))
ct=np.empty((0,3))
order_t=np.empty((0,3))
for i in range(3000):
    tmp= np.array([[random.randrange(0,300) for j in range(3)]])
    x=tmp[0,0]
    if x<100:
        at=np.append(at,np.array([[1, 0, 0]]),axis=0)
        ax=np.append(ax,tmp,axis=0)
    elif x<200:
        bt=np.append(bt,np.array([[0, 1, 0]]),axis=0)
        bx=np.append(bx,tmp,axis=0)
    elif x<300:
        ct=np.append(ct,np.array([[0, 0, 1]]),axis=0)
        cx=np.append(cx,tmp,axis=0)
order_t=np.append(order_t,at,axis=0)
order_t=np.append(order_t,bt,axis=0)
order_t=np.append(order_t,ct,axis=0)

order_xyz=np.append(order_xyz,ax,axis=0)
order_xyz=np.append(order_xyz,bx,axis=0)
order_xyz=np.append(order_xyz,cx,axis=0)

ax=np.empty((0,3))
bx=np.empty((0,3))
cx=np.empty((0,3))

at=np.empty((0,3))
bt=np.empty((0,3))
ct=np.empty((0,3))

for i in range(1000):
    tmp= np.array([[random.randrange(0,300) for j in range(3)]])
    x=tmp[0,0]
    if x<100:
        at=np.append(at,np.array([[1, 0, 0]]),axis=0)
        ax=np.append(ax,tmp,axis=0)
    elif x<200:
        bt=np.append(bt,np.array([[0, 1, 0]]),axis=0)
        bx=np.append(bx,tmp,axis=0)
    elif x<300:
        ct=np.append(ct,np.array([[0, 0, 1]]),axis=0)
        cx=np.append(cx,tmp,axis=0)
order_t=np.append(order_t,at,axis=0)
order_t=np.append(order_t,bt,axis=0)
order_t=np.append(order_t,ct,axis=0)

order_xyz=np.append(order_xyz,ax,axis=0)
order_xyz=np.append(order_xyz,bx,axis=0)
order_xyz=np.append(order_xyz,cx,axis=0)



ax=np.empty((0,3))
bx=np.empty((0,3))
cx=np.empty((0,3))

at=np.empty((0,3))
bt=np.empty((0,3))
ct=np.empty((0,3))

for i in range(1000):
    tmp= np.array([[random.randrange(0,300) for j in range(3)]])
    x=tmp[0,0]
    if x<100:
        at=np.append(at,np.array([[1, 0, 0]]),axis=0)
        ax=np.append(ax,tmp,axis=0)
    elif x<200:
        bt=np.append(bt,np.array([[0, 1, 0]]),axis=0)
        bx=np.append(bx,tmp,axis=0)
    elif x<300:
        ct=np.append(ct,np.array([[0, 0, 1]]),axis=0)
        cx=np.append(cx,tmp,axis=0)
order_t=np.append(order_t,at,axis=0)
order_t=np.append(order_t,bt,axis=0)
order_t=np.append(order_t,ct,axis=0)

order_xyz=np.append(order_xyz,ax,axis=0)
order_xyz=np.append(order_xyz,bx,axis=0)
order_xyz=np.append(order_xyz,cx,axis=0)

input_data=order_xyz
t =order_t

## Input Data Normalize  (0~1)

정규화 식


<img src = "../simple_network/Data/images/normalize.png" width = "200" height = "75">



In [3]:
input_max=299
input_min=0
de=input_max-input_min
normalize_input=np.zeros((5000,3),dtype=float)
for i in range(5000):
    for j in range(3):
        normalize_input[i,j]=(input_data[i,j]-input_min)/de
print(input_data)
print(normalize_input)

[[238. 194.  47.]
 [213. 149. 169.]
 [111. 271. 148.]
 ...
 [161.   7.  19.]
 [263. 190. 168.]
 [238. 130.  53.]]
[[0.79598662 0.64882943 0.15719064]
 [0.71237458 0.49832776 0.56521739]
 [0.37123746 0.90635452 0.49498328]
 ...
 [0.53846154 0.02341137 0.06354515]
 [0.87959866 0.63545151 0.56187291]
 [0.79598662 0.43478261 0.17725753]]


## input data input_data_set.npz 파일에 저장

np.savez() --> 여러개의 배열을 1개의 압축되지 않은 *.npz 포맷 파일로 저장하기 (Save several arrays into a single file in uncompressed .npz format)

In [4]:
# input data -> before normalization
# np.savez("../simple_network/Data/input_data_set.npz", input_data)
# np.savez("../simple_network/Data/t_set.npz", t)

# input data -> after normalization
np.savez("../simple_network/Data/input_data_set.npz", normalize_input)
np.savez("../simple_network/Data/t_set.npz", t)


In [ ]:
# colum vector로 csv파일에 저장
# np.savetxt("input.csv", normalize_input, delimiter="\n")

np.savetxt("input.csv", normalize_input, delimiter=",")
np.savetxt("ttt.csv", t, delimiter=",")


In [ ]:
np.savetxt("no_normal_input.csv", input_data, delimiter="\n")

#### Input Data 파일 읽기 테스트

np.savez()를 사용하여 numpy array 형 변수 읽어오기


In [5]:
read_input=np.load("../simple_network/Data/input_data_set.npz", allow_pickle=True)
read_t=np.load("../simple_network/Data/t_set.npz", allow_pickle=True)
r_input_data=read_input["arr_0"]
r_t_data=read_t["arr_0"]
print(r_input_data)
print(r_t_data)

[[0.79598662 0.64882943 0.15719064]
 [0.71237458 0.49832776 0.56521739]
 [0.37123746 0.90635452 0.49498328]
 ...
 [0.53846154 0.02341137 0.06354515]
 [0.87959866 0.63545151 0.56187291]
 [0.79598662 0.43478261 0.17725753]]
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]


## 가중치 W, 편향 B  생성 ##
1. 정규분포를 따르는 랜덤수로 생성   (np.random.randn()을 사용하면 "평균 = 0, 표준편차 = 1"인 랜덤수가 생성됨.)
    
    0.1을 곱해주는 이유: w의 초기값이크면 gradient vanishing 문제가 발생할 수 있음.

    따라서 초기 가중치 값에 0.1을 곱해 표준편차를 0.1로 만들어줌.


In [6]:
weight_init_std=0.1
params={}
params['W1']=weight_init_std*np.random.randn(3,4)
params['B1']=np.zeros(4)
params['W2']=weight_init_std*np.random.randn(4,4)
params['B2']=np.zeros(4)
params['W3']=weight_init_std*np.random.randn(4,3)
params['B3']=np.zeros(3)


2. constant로 생성

In [ ]:
# params['W1']=np.zeros((3,4))
# params['B1']=np.zeros(4)
# params['W2']=np.zeros((4,4))
# params['B2']=np.zeros(4)
# params['W3']=np.zeros((4,3))
# params['B3']=np.zeros(3)

# params['W1'].fill(0.1)
# params['W2'].fill(0.1)
# params['W3'].fill(0.1)


3. 균일분포를 따르는 랜덤수로 생성

In [ ]:
# weight_init_std=0.01
# params={}
# params['W1']=np.random.uniform(-1,1,(3,4))
# params['B1']=np.zeros(4)
# params['W2']=np.random.uniform(-1,1,(4,4))
# params['B2']=np.zeros(4)
# params['W3']=np.random.uniform(-1,1,(4,3))
# params['B3']=np.zeros(3)
# print(params)

## 가중치 W, 편향 B weight_bias.npz 파일에 저장

np.savez() --> 여러개의 배열을 1개의 압축되지 않은 *.npz 포맷 파일로 저장하기 (Save several arrays into a single file in uncompressed .npz format)

In [7]:
np.savez("../simple_network/Data/weight_bias.npz", **params)

##### dictionary형 변수 csv파일에 저장

In [ ]:
# open a file in write mode
# with open('../simple_network/Data/weight_bias.csv', 'w', newline='') as f:
#     # create a csv writer
#     writer = csv.writer(f)
#     # write the keys of the dictionary as the header row
#     writer.writerow(params.keys())
#     # write the values of the dictionary as a single row
#     writer.writerow(params.values())

new_params={}
new_params['W1']=params['W1']
new_params['W2']=params['W2']
new_params['W3']=params['W3']
with open('eeeeeeeee.csv', 'w', newline='') as csvfile:
    # Create a CSV writer
    writer = csv.writer(csvfile)

    # Write the values of the W1, W2, and W3 arrays to the CSV file
    for key, value in new_params.items():
        writer.writerows(value)

npz 변수 파일 불러오기

np.load("파일명",allow_pickle=True)

In [8]:
my_dictionary = np.load("../simple_network/Data/weight_bias.npz", allow_pickle=True)
paaa=dict(my_dictionary)
print(paaa)
print(params)

{'W1': array([[-0.10790143, -0.12389922, -0.02870852, -0.00758739],
       [-0.01877527, -0.01418248,  0.06568369,  0.13711101],
       [ 0.07620515, -0.10259364, -0.06834094,  0.1009164 ]]), 'B1': array([0., 0., 0., 0.]), 'W2': array([[-0.2113364 , -0.00938436, -0.04055604, -0.00323215],
       [-0.00483237,  0.13771809, -0.04705553, -0.0316061 ],
       [-0.13500221, -0.10569201,  0.01449941, -0.20003833],
       [ 0.18467875, -0.19403669, -0.09042695,  0.16982677]]), 'B2': array([0., 0., 0., 0.]), 'W3': array([[ 0.06917473, -0.0479682 ,  0.22608074],
       [ 0.08138034, -0.19442319, -0.14452055],
       [-0.13520226,  0.16875547, -0.12732817],
       [-0.06124496, -0.09132541,  0.01335419]]), 'B3': array([0., 0., 0.])}
{'W1': array([[-0.10790143, -0.12389922, -0.02870852, -0.00758739],
       [-0.01877527, -0.01418248,  0.06568369,  0.13711101],
       [ 0.07620515, -0.10259364, -0.06834094,  0.1009164 ]]), 'B1': array([0., 0., 0., 0.]), 'W2': array([[-0.2113364 , -0.00938436, -0.0